---
title: 'Supporting Information: Use of a filter cartridge combined with intra-cartridge bead beating
  improves detection of microbial DNA from water samples'
author: "Masayuki Ushio"
output:
  pdf_document:
    fig_caption: yes
  word_document: default
header-includes:
  - \usepackage{caption}
  - \captionsetup[figure]{labelformat=empty}
  - \pagenumbering{gobble} #### to delete page number
---

# Contents:
* **Figure S1**| Images of Sterivex filter cartridge and zirconia beads, the procedure to add zirconia beads into Sterivex, and DNA extraction from Sterivex
* **Figure S2**| The relationship between DNA yield quantified by NanoDrop and bead amount
* **Figure S3**| Rarefaction curve of sequence reads of each sample
* **Figure S4**| Prokaryotic phyla detected in the field negative controls
* **Figure S5**| The relationship between DNA yield quantified by NanoDrop and DNA extraction method
* **Figure S6**| The number of ASVs with more than 100 copies/ml water
* **Figure S7**| Non-metric dimensional scaling (NMDS) for ASVs from all study sites
* **Figure S8**| Method-specific ASVs for each DNA extraction method based on an alternative, quantitative criterion
* **Table S1**| Sample metadata and summary for DADA2 sequence processing
* **Table S2**| Prokaryote standard DNA sequences including primer regions
* **Table S3**| Taxa assignments of method-specific ASVs

<center>

![
**Figure S1**| Images of Sterivex\texttrademark\ filter cartridge and zirconia beads. (**a**) Sterivex cartridge filter without zirconia beads. (**b**) Sterivex filter cartridge with inlet/outlet caps (inlet, Luer Fitting VRMP6; outlet, Luer Fitting VRSP6). (**c**) Enlarged image of $\phi$ 0.5 mm zirconia beads. (**d**) Sterivex\texttrademark\ filter cartridge with a rolled filter paper (ADVANTEC, 5A 90 mm). (**e**) A hand-made scoop. The scoop is used to add/measure 1 g of zirconia beads. (**f**) RNAlater solution was removed using QIAvac system (Qiagen, Hilden, Germany) before DNA extraction. (**g**) The lysate was transferred into a new 2-ml tube from the inlet of the filter cartridge by centrifugation. A capless 2-ml tube was lightly attached by a clean tape to the outlet of the cartridge before the centrifugation.
](../0_RawFigs/RefmtFigs/FigS_BeadsPic_v3.pdf){width=70%}

</center>

<center>

![
**Figure S2**| The relationship between DNA yield quantified by NanoDrop and bead amount. Water samples were collected from a pond adjacent to an experimental forest in the Center for Ecological Research, Kyoto University (34$^\circ$ 58$'$ 18$''$ N, 135$^\circ$ 57$'$ 32$''$ E) in February 2017. Ten ml of water samples were collected from the pond and filtered using the cartridge filters. The amounts of beads inside the filter cartridge were 0 (No beads), 0.05, 0.2, 1 and 2 g. The number of replicates for each category was three. In total, 15 samples were included in the preliminary test (i.e., three replicate and five treatments). After the filtration, DNAs were extracted using a DNeasy\textregistered\ Blood & Tissue Kit (Qiagen, Hilden, Germany) as described in the main text (see DNA extraction in Methods section). The yields of extracted DNA were quantified using a NanoDrop spectrometer (ThermoFisher Scientific, Waltham, Massachusetts, USA).
](../0_RawFigs/RefmtFigs/FigS_Beads.pdf)

</center>

\newpage
<center>

![
**Figure S3**| Rarefaction curve of sequence reads of each sample. Different colours indicate different DNA extraction methods.
](../0_RawFigs/RefmtFigs/FigS_Rarefy.pdf)

</center>

<center>

![
**Figure S4**| Sequence reads detected in the field negative controls. The DNA copy numbers detected in a field negative control were divided by the mean DNA copy number of positive samples in each method. DNA copy numbers detected in field negative controls were less than 0.07%. In addition, there were no qualitative differences in DNA copy numbers or phylum detected among DNA extraction methods.
](../0_RawFigs/RefmtFigs/FigS_NCBarProp.pdf)

</center>

<center>

![
**Figure S5**| The relationship between DNA yield quantified by NanoDrop and DNA extraction method for the lake and river samples. Different letters indicate significant differences between the DNA extraction methods.
](../0_RawFigs/RefmtFigs/FigS_NanoDrop.pdf)

</center>


<center>

![
**Figure S6**| The number of ASVs with more than 100 copies per ml water for each treatment. Different letters indicate significant differences between the DNA extraction methods.
](../0_RawFigs/RefmtFigs/Fig_Div100.pdf)

</center>

<center>

![
**Figure S7**| Nonmetric dimensional scaling (NMDS) of the prokaryotic community composition. All ASVs from all sites were used for (**a**) and only repeatedly detected ASVs from all sites were used for (**b**). “$P$” indicates the significance of the difference among methods in the overall community composition.
](../0_RawFigs/RefmtFigs/Fig_NMDS2.pdf)

</center>



<center>

![
**Figure S8**| Method-specific ASVs for each DNA extraction method based on an alternative, quantitative criterion. The alternative, more quantitative criterion was applied and used to test whether the results remained qualitatively unchanged. First, mean value, standard deviation, and coefficient of variation (C.V.) of each microbial ASV were calculated. Then, the criterion for method-specific ASV was as follows: (1) the mean value of the method-specific ASV is two times as large as that of the ASV detected by other methods and (2) the C.V. of the method-specific ASV is less than one. ASVs satisfying criteria (1) and (2) are ASVs that are predominantly and reliably detected by a method, and thus the combination of these can be an alternative criterion for method-specific ASVs.
](../0_RawFigs/RefmtFigs/FigS_Rare2.pdf){width=90%}

</center>
